---

- name: install dependencies
  package:
    name: ["iptables", "gawk", "iproute"]
    state: present

- name: install ferm
  dnf:
    name: "{{ ferm_rpm }}"
    disable_gpg_check: yes
    state: present 
